version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=rfin
      - POSTGRESQL_PASSWORD=rfin
      - POSTGRESQL_DATABASE=rfin